const data = [
  {
    id: 5,
    type: "Project",
    idName: "Clock",
    name: "Clock",
    briefDesc: "Javascript Clock",
    fullDescription: "Simple Javascript analog and digital clock",
    languages: ["HTML", "CSS", "Javascript"],
    demoBack: null,
    demoFront: "https://patrickrgrady81.github.io/MiniJS/002%20Clock/index.html",
    back: null,
    front: "https://github.com/patrickrgrady81/MiniJS/tree/master/002%20Clock",
    image: "Clock.png",
  },
    {
    id: 1,
    type: "Project",
    idName: "Fresco",
    name: "Fresco",
    briefDesc: "A simple painting program",
    fullDescription: "Choose your colors and draw whetever you like.",
    languages: ["HTML", "CSS", "Javascript"],
    demoBack: null,
    demoFront: "https://patrickrgrady81.github.io/MiniJS/005%20Fresco/index.html",
    back: null,
    front: "https://github.com/patrickrgrady81/MiniJS/tree/master/005%20Fresco",
    image: "Fresco.png",
  },
      {
    id: 2,
    type: "Project",
    idName: "Breakout",
    name: "Breakout",
    briefDesc: "Javascript Breakout clone",
    fullDescription: "Break them bricks with this interesting javascript game.",
    languages: ["HTML", "CSS", "Javascript"],
    demoBack: null,
    demoFront: "https://patrickrgrady81.github.io/MiniJS/004%20Breakout/index.html",
    back: null,
    front: "https://github.com/patrickrgrady81/MiniJS/tree/master/004%20Breakout",
    image: "Breakout.png",
  },
  {
    id: 3,
    type: "Project",
    idName: "Novel",
    name: "Novel Ideas",
    briefDesc: "Book App",
    fullDescription: "Search , save and chat about books. Save books to your profile for later viewing. See descriptions of books. Use the built in forums to discuss, share and review books.",
    languages: ["Ruby on Rails"],
    demoBack: "https://novel-ideas.herokuapp.com/",
    demoFront: null,
    back: "https://github.com/patrickrgrady81/novel-ideas",
    front: null,
    image: "NovelIdeas.png",
  },
  {
    id: 4,
    type: "Project",
    idName: "Snake",
    name: "PaddySnake",
    briefDesc: "Snake Game",
    fullDescription: "Classic Snake game with a few tweaks. Play with your friends to see who can get the highest score. There is a scoreboard to keep track of all the high scores",
    languages: ["Ruby on Rails", "Javascript"],
    demoBack: "https://paddysnake.herokuapp.com/",
    demoFront: "https://patrickrgrady81.github.io/Snake/",
    back: "https://github.com/patrickrgrady81/Peeker-back",
    front: "https://github.com/patrickrgrady81/Snake",
    image: "PaddySnake.png",
  },
  {
    id: 0,
    type: "Project",
    idName: "Peeker",
    name: "Peeker",
    briefDesc: "Video Poker",
    fullDescription: "This project is still in development. Try your luck with this video poker game. Bet up to 5 credits, discard the ones you don't want and try to get the best hand. Good Luck!",
    languages: ["HTML", "CSS", "React"],
    demoBack: null,
    demoFront: "https://pg-peeker.netlify.app/",
    back: null,
    front: "https://github.com/patrickrgrady81/peeker",
    image: "Peeker.png",
  },
]

export default data

